const bannedText: string[] = [
  // dp specific tags to block
  '#pompouspep',
  '#pompep',
  // TODO: add other problematic ships (and sadly learn the names of those *sigh*)

  // obvious
  ' nsfw ',
  '#nsfw',
  ' anal ',
  ' anus ',
  ' ballsack ',
  ' biatch ',
  ' blowjob ',
  ' blow job ',
  ' bollock ',
  ' bollok ',
  ' boner ',
  ' boob ',
  ' bum ',
  ' butt ',
  ' buttplug ',
  ' clitoris ',
  ' cock ',
  ' coon ',
  ' cum ',
  ' cumming ',
  ' cunt ',
  ' dick ',
  ' dildo ',
  ' dyke',
  ' fag ',
  ' faggot ',
  ' fellate ',
  ' fellatio ',
  ' felching ',
  ' fudgepacker ',
  ' fudge packer ',
  ' hell ',
  ' homo ',
  ' jizz ',
  ' knobend ',
  ' knob end ',
  ' labia ',
  ' muff ',
  ' nigger ',
  ' nigga ',
  ' penis ',
  ' piss ',
  ' poop ',
  ' prick ',
  ' pube ',
  ' pussy ',
  ' scrotum ',
  ' slut ',
  ' smegma ',
  ' spunk ',
  ' tosser ',
  ' turd ',
  ' twat ',
  ' vagina ',
  ' wank ',
  ' whore ',
  '#yaoi',
  '#r34',
  '#rule43',
]

// Exclude posts from these users
const bannedUsers: string[] = [
  'did:plc:ju7elc27naswr6mnvpevfqxn', // sperezart.bsky.social (nsfw artist, sorry, trying to keep the feed clean)
  'did:plc:rypydv2x5sswveg6haa4vbrc', // evercras.bsky.social (nsfw artist, sorry, trying to keep the feed clean)
]

export { bannedText, bannedUsers }
